#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-ZenTest
Version  : 4.11.1
Release  : 14
URL      : https://rubygems.org/downloads/ZenTest-4.11.1.gem
Source0  : https://rubygems.org/downloads/ZenTest-4.11.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-ZenTest-bin
BuildRequires : ruby
BuildRequires : rubygem-hoe
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rdoc

%description
= ZenTest
home :: https://github.com/seattlerb/zentest
rdoc :: http://docs.seattlerb.org/ZenTest

%package bin
Summary: bin components for the rubygem-ZenTest package.
Group: Binaries

%description bin
bin components for the rubygem-ZenTest package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n ZenTest-4.11.1
gem spec %{SOURCE0} -l --ruby > rubygem-ZenTest.gemspec

%build
export LANG=C
gem build rubygem-ZenTest.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
ZenTest-4.11.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/ZenTest-4.11.1
ruby -v -I.:lib:test test*/test_*.rb
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/ZenTest-4.11.1.gem
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/.autotest
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/History.txt
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/Manifest.txt
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/README.txt
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/articles/Article.css
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/articles/getting_started_with_autotest.html
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/articles/how_to_use_zentest.txt
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/bin/autotest
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/bin/multigem
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/bin/multiruby
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/bin/multiruby_setup
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/bin/unit_diff
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/bin/zentest
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/example.txt
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/example1.rb
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/example2.rb
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/example_dot_autotest.rb
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/lib/autotest.rb
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/lib/autotest/autoupdate.rb
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/lib/autotest/bundler.rb
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/lib/autotest/isolate.rb
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/lib/autotest/once.rb
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/lib/autotest/preload.rb
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/lib/autotest/rcov.rb
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/lib/autotest/restart.rb
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/lib/autotest/timestamp.rb
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/lib/focus.rb
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/lib/functional_test_matrix.rb
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/lib/multiruby.rb
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/lib/unit_diff.rb
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/lib/zentest.rb
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/lib/zentest_mapping.rb
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/test/test_autotest.rb
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/test/test_focus.rb
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/test/test_unit_diff.rb
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/test/test_zentest.rb
/usr/lib64/ruby/gems/2.3.0/gems/ZenTest-4.11.1/test/test_zentest_mapping.rb
/usr/lib64/ruby/gems/2.3.0/specifications/ZenTest-4.11.1.gemspec

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/autotest
/usr/bin/multigem
/usr/bin/multiruby
/usr/bin/multiruby_setup
/usr/bin/unit_diff
/usr/bin/zentest
