#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-ZenTest
Version  : 4.11.0
Release  : 9
URL      : https://rubygems.org/downloads/ZenTest-4.11.0.gem
Source0  : https://rubygems.org/downloads/ZenTest-4.11.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-ZenTest-bin
BuildRequires : ruby
BuildRequires : rubygem-hoe
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rdoc

%description
= ZenTest
home :: https://github.com/seattlerb/zentest
rdoc :: http://docs.seattlerb.org/ZenTest

%package bin
Summary: bin components for the rubygem-ZenTest package.
Group: Binaries

%description bin
bin components for the rubygem-ZenTest package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n ZenTest-4.11.0
gem spec %{SOURCE0} -l --ruby > rubygem-ZenTest.gemspec

%build
gem build rubygem-ZenTest.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
ZenTest-4.11.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/ZenTest-4.11.0
ruby -v -I.:lib:test test*/test_*.rb
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/ZenTest-4.11.0.gem
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/AutoUpdate/cdesc-AutoUpdate.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/AutoUpdate/sleep_time%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/AutoUpdate/update_cmd%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/Bundler/cdesc-Bundler.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/Isolate/cdesc-Isolate.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/Isolate/dir%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/Once/cdesc-Once.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/Preload/cdesc-Preload.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/Preload/glob%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/Preload/glob-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/RCov/cdesc-RCov.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/RCov/command%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/RCov/options%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/RCov/pattern%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/Restart/cdesc-Restart.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/Timestamp/cdesc-Timestamp.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/add_discovery-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/add_exception-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/add_hook-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/add_mapping-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/add_sigint_handler-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/add_sigquit_handler-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/all_good-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/autodiscover-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/cdesc-Autotest.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/class_map-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/clear_exceptions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/clear_mappings-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/completed_re-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/consolidate_failures-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/debug-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/exceptions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/extra_class_map-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/extra_files-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/failed_results_re-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/files_matching-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/files_to_test-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/find_directories-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/find_files-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/find_files_to_test-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/find_order-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/get_to_green-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/handle_results-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/hook-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/interrupted-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/known_files-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/last_mtime-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/latest_results-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/libs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/make_test_cmd-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/new_hash_of_arrays-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/old_run_tests-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/options-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/order-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/output-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/parse_options-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/path_to_classname-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/prefix-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/remove_exception-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/remove_mapping-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/reorder-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/rerun_all_tests-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/reset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/restart-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/results-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/ruby-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/ruby_cmd-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/run-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/run_tests-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/runner-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/sleep-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/tainted%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/tainted-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/test_files_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/test_mappings-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/testlib-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/testprefix-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/unit_diff-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/wait_for_changes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Autotest/wants_to_quit-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/FunctionalTestMatrix/action-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/FunctionalTestMatrix/action-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/FunctionalTestMatrix/cdesc-FunctionalTestMatrix.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/FunctionalTestMatrix/matrix-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/FunctionalTestMatrix/matrix-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Module/blur-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Module/cdesc-Module.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Module/focus-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Module/focus_re-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Module/zentest-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/Multiruby/cdesc-Multiruby.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/UnitDiff/cdesc-UnitDiff.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/UnitDiff/diff-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/UnitDiff/massage-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/UnitDiff/parse_diff-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/UnitDiff/parse_input-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/UnitDiff/unit_diff-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/UnitDiff/unit_diff-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/ZenTest/add_missing_method-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/ZenTest/analyze-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/ZenTest/analyze_impl-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/ZenTest/analyze_test-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/ZenTest/autotest-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/ZenTest/cdesc-ZenTest.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/ZenTest/convert_class_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/ZenTest/create_method-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/ZenTest/fix-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/ZenTest/generate_code-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/ZenTest/get_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/ZenTest/get_inherited_methods_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/ZenTest/get_methods_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/ZenTest/is_test_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/ZenTest/load_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/ZenTest/methods_and_tests-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/ZenTest/missing_methods-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/ZenTest/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/ZenTest/process_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/ZenTest/result-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/ZenTest/scan_files-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/ZenTest/usage-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/ZenTest/usage_with_exit-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/ZenTestMapping/cdesc-ZenTestMapping.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/ZenTestMapping/munge-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/ZenTestMapping/normal_to_test-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/ZenTestMapping/test_to_normal-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/ZenTestMapping/unmunge-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/articles/page-how_to_use_zentest_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/page-History_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/page-Manifest_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/page-README_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/ZenTest-4.11.0/ri/page-example_txt.ri
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/.autotest
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/.gemtest
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/History.txt
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/Manifest.txt
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/README.txt
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/articles/Article.css
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/articles/getting_started_with_autotest.html
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/articles/how_to_use_zentest.txt
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/bin/autotest
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/bin/multigem
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/bin/multiruby
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/bin/multiruby_setup
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/bin/unit_diff
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/bin/zentest
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/example.txt
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/example1.rb
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/example2.rb
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/example_dot_autotest.rb
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/lib/autotest.rb
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/lib/autotest/autoupdate.rb
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/lib/autotest/bundler.rb
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/lib/autotest/isolate.rb
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/lib/autotest/once.rb
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/lib/autotest/preload.rb
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/lib/autotest/rcov.rb
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/lib/autotest/restart.rb
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/lib/autotest/timestamp.rb
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/lib/focus.rb
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/lib/functional_test_matrix.rb
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/lib/multiruby.rb
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/lib/unit_diff.rb
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/lib/zentest.rb
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/lib/zentest_mapping.rb
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/test/test_autotest.rb
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/test/test_focus.rb
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/test/test_unit_diff.rb
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/test/test_zentest.rb
/usr/lib64/ruby/gems/2.2.0/gems/ZenTest-4.11.0/test/test_zentest_mapping.rb
/usr/lib64/ruby/gems/2.2.0/specifications/ZenTest-4.11.0.gemspec

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/autotest
/usr/bin/multigem
/usr/bin/multiruby
/usr/bin/multiruby_setup
/usr/bin/unit_diff
/usr/bin/zentest
